platform :ios, '8.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'Speed' do
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.7'
pod 'FMDB'
pod 'SVProgressHUD'
pod 'IQKeyboardManager'
pod 'MJExtension'
pod 'UMengAnalytics-NO-IDFA'
#pod 'RDVTabBarController'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Masonry', '~> 1.0.2'
pod 'YYModel','~> 1.0.4'
end












