var templatenav = [
// 一级菜单
    {
        "title":"常用菜单",
        // "href":"html/4.html",
        // 二级菜单
        "children":[
            {
                "title":"角色管理",
                "href":"html/roleManage.html",
                "id":"roleManage",
                "children":[]
            },
            {
                "title":"菜单管理",
                "href":"html/menu.html",
                "id":"menu",
                "children":[]
            },
            {
                "title":"用户管理",
                "href":"html/userManage.html",
                "id":"userManage",
                "children":[]
            },
            {
                "title":"单位管理",
                "href":"html/unitManage.html",
                "id":"unitManage",
                "children":[]
            },
            {
                "title":"日志管理",
                "href":"html/logManage.html",
                "id":"logManage",
                "children":[]
            },
            {
                "title":"二级1",
                "href":"html/2.html",
                "children":[
                    {
                        "title":"三级1",
                        "href":"html/1.html",
                        "id":"sanji1"
                    },
                    {
                        "title":"三级2",
                        "href":"html/2.html",
                        "id":"sanji2"
                    },
                    {
                        "title":"三级3",
                        "href":"html/3.html",
                        "id":"sanji3"
                    },
                ]
            },
        ]
    },
    {
        "title":"接口",
        // "href":"html/4.html",
        // 二级菜单
        "children":[
            {
                "title":"推送",
                "href":"html/push.html",
                "id":"push",
                "children":[]
            },
            {
                "title":"测试接口",
                "href":"html/yemian.html",
                "id":"yemian",
                "children":[]
            },
        ]
    },
]

/*var templatenav = [
// 一级菜单
    {
        "title":"日志",
        "href":"html/log.html",
        "id":"log"
    },
    {
        "title":"一级2",
        "href":"html/2.html",
        "id":"yiji2"
    },
    {
        "title":"一级3",
        "href":"html/3.html",
        "id":"yiji3"
    },
    {
        "title":"一级4",
        "href":"html/4.html",
        // 二级菜单
        "children":[
            {
                "title":"二级1",
                "href":"html/1.html",
                "id":"erji1"
            },
            {
                "title":"二级2",
                "href":"html/2.html",
                "children":[
                    {
                        "title":"三级1",
                        "href":"html/1.html",
                        "id":"sanji1"
                    },
                    {
                        "title":"三级2",
                        "href":"html/2.html",
                        "id":"sanji2"
                    },
                    {
                        "title":"三级3",
                        "href":"html/3.html",
                        "id":"sanji3"
                    },
                ]
            },
            {
                "title":"二级3",
                "href":"html/3.html",
                "id":"erji3"
            },
        ]
    },
]*/